MOUSEKEY_ENABLE = no     # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE      = yes    # Enable VIA
VIAL_ENABLE     = yes
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
WPM_ENABLE 		= yes
VIAL_INSECURE   = yes
QMK_SETTINGS    = no
COMBO_ENABLE    = no
KEY_OVERRIDE_ENABLE = no
